USE `DA_PTTK`;

-- PROC DEM SO LUONG PHONG TRONG
DELIMITER $$  
drop procedure if exists CAPNHAT_LOAIPHONG_COUNT;
CREATE PROCEDURE CAPNHAT_LOAIPHONG_COUNT()
BEGIN
	DECLARE SL INT;
	SET SQL_SAFE_UPDATES = 0;
    
    SET SL=(SELECT COUNT(MAPHONG) FROM PHONG WHERE LOAIPHONG = 'PHONG DOI' AND TINHTRANG='TRONG');
    UPDATE LOAIPHONG_COUNT SET SOLUONGPHONGTRONG = SL WHERE LOAIPHONG = 'PHONG DOI';
    
    SET SL=(SELECT COUNT(MAPHONG) FROM PHONG WHERE LOAIPHONG = 'PHONG DON' AND TINHTRANG='TRONG');
    UPDATE LOAIPHONG_COUNT SET SOLUONGPHONGTRONG = SL WHERE LOAIPHONG = 'PHONG DON';
    
    SET SL=(SELECT COUNT(MAPHONG) FROM PHONG WHERE LOAIPHONG = 'PHONG GIA DINH' AND TINHTRANG='TRONG');
    UPDATE LOAIPHONG_COUNT SET SOLUONGPHONGTRONG = SL WHERE LOAIPHONG = 'PHONG GIA DINH';
    SET SQL_SAFE_UPDATES = 1;
End $$
DELIMITER ;
CALL CAPNHAT_LOAIPHONG_COUNT();
SELECT * FROM LOAIPHONG_COUNT;

-- KHACH HANG DAT PHONG (MAKH, LOAI PHONG, SL, OUT MSG)
DELIMITER $$  
drop procedure if exists DAT_PHONG;
CREATE PROCEDURE DAT_PHONG(
	IN NMAKH varchar(5) ,
    IN NLOAIPHONG VARCHAR(50),
	IN NSL INT,
    IN NMANV VARCHAR(5),
    OUT MSG VARCHAR(5))
BEGIN
	DECLARE n INT;
	IF NSL<1
    THEN
		SELECT 'SO LUONG PHAI LON HON 0' AS '';
        ROLLBACK;
	ELSEIF NLOAIPHONG NOT IN ('PHONG DON', 'PHONG DOI', 'PHONG GIA DINH')
	THEN 
		SELECT 'LOAI PHONG KHONG PHU HOP' AS '';
        ROLLBACK;
	ELSEIF NSL > (SELECT SOLUONGPHONGTRONG FROM LOAIPHONG_COUNT WHERE LOAIPHONG=NLOAIPHONG)
    THEN
		SELECT 'SO LUONG PHONG TRONG KHONG DU' AS '';
        ROLLBACK;
	ELSEIF NMAKH NOT IN (SELECT MAKH FROM PHIEUDATPHONG) OR (SELECT COUNT(TINHTRANG) FROM PHIEUDATPHONG WHERE MAKH=NMAKH AND TINHTRANG ='DANG DAT')=0
    -- NEU KHACH HANG CHUA CO PHIEU DAT PHONG THI TIEN HANH TAO PHIEU DAT PHONG
    THEN
		CALL THEM_PHIEUDATPHONG(CURDATE(), NULL, NSL, NULL, NMAKH, NMANV, @NMAPDP);
	ELSE
    -- NEU KHACH HANG DA CO PHIEU DAT THI TAO CHI TIET PHIEU DAT MOI
		SET n = 0;
		WHILE n <NSL DO
			CALL LAY_MAPHONG_TRONG(NLOAIPHONG, @MAPHONGTRONG);
			CALL LAY_MAPHIEUDATPHONG(NMAKH, @MAPHIEU);
			CALL THEM_CHITIETPHIEUDAT(NLOAIPHONG,NULL,NULL,NULL,NULL,NULL,@MAPHONGTRONG,@MAPHIEU, @MACTPD);
			CALL CAPNHAT_TT_PHONG(@MAPHONGTRONG, 'DANG DAT');
			SET n = n +1;
		END WHILE;
        SELECT @MACTPD;
	END IF;
End $$
DELIMITER ;
CALL DAT_PHONG('KH005', 'PHONG DON', 2,'LT001',@MSG);