USE `DA_PTTK`;

-- XEM THONG TIN KHACH HANG
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_TT_KHACHHANG;
CREATE PROCEDURE XEM_TT_KHACHHANG(IN NMAKH VARCHAR(5))
BEGIN
	IF NMAKH NOT IN (SELECT MAKH FROM KHACHHANG)
	THEN   
		BEGIN 
			SELECT 'KHACH HANG KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
	SELECT * FROM KHACHHANG WHERE MAKH=NMAKH;
    END IF;
END$$
DELIMITER ;
CALL XEM_TT_KHACHHANG('KH001');

-- LICH SU PHIEUDATPHONG
DELIMITER $$  
drop procedure if exists XEM_DS_PHIEUDATPHONG_THEO_MAKH;
CREATE PROCEDURE XEM_DS_PHIEUDATPHONG_THEO_MAKH(IN NMAKH VARCHAR(5))
BEGIN
	SELECT * FROM PHIEUDATPHONG WHERE MAKH=NMAKH;
End $$
DELIMITER ;
CALL XEM_DS_PHIEUDATPHONG_THEO_MAKH('KH004');

-- LICH SU HOA DON
DELIMITER $$  
drop procedure if exists XEM_DS_HOADON_THEO_MAKH;
CREATE PROCEDURE XEM_DS_HOADON_THEO_MAKH(IN NMAKH VARCHAR(5))
BEGIN
	SELECT * FROM HOADON WHERE MAKH=NMAKH;
End $$
DELIMITER ;
CALL XEM_DS_HOADON_THEO_MAKH('KH001');

-- XEM CHI TIET PHIEUDAT THEO MAPDP
DELIMITER $$  
drop procedure if exists XEM_DS_CHITIETPHIEUDAT_THEO_MAPDP;
CREATE PROCEDURE XEM_DS_CHITIETPHIEUDAT_THEO_MAPDP(IN NMAPDP VARCHAR(5))
BEGIN
	SELECT * FROM CHITIETPHIEUDAT WHERE MAPDP=NMAPDP;
End $$
DELIMITER ;

CALL XEM_DS_CHITIETPHIEUDAT_THEO_MAPDP('DP001');

-- XEM DS LICH SU DICH VU DA MUA
DELIMITER $$  
drop procedure if exists XEM_DS_DV_CUA_PDP;
CREATE PROCEDURE XEM_DS_DV_CUA_PDP(IN NMAPDP VARCHAR(5))
BEGIN
	SELECT DISTINCT DVP.* FROM PHIEUDATPHONG PDP, CHITIETPHIEUDAT CTPD, DICHVUCUAPHONG DVP WHERE PDP.MAPDP=NMAPDP AND CTPD.MAPDP= PDP.MAPDP AND DVP.MAPHONG = CTPD.MAPHONG;
End $$
DELIMITER ;

CALL XEM_DS_DV_CUA_PDP('DP001');