USE `DA_PTTK`;
-- XEM DS_PHONG THEO YEU CAU
DELIMITER $$  
drop procedure if exists XEM_DS_PHONG_THEO_DK;
CREATE PROCEDURE XEM_DS_PHONG_THEO_DK(IN NLOAIPHONG VARCHAR(20), IN NTINHTRANG VARCHAR(20))
BEGIN
	IF NLOAIPHONG IS NULL AND NTINHTRANG IS NULL
    THEN
		SELECT * FROM PHONG;
	ELSEIF NTINHTRANG IS NULL
	THEN   
		SELECT * FROM PHONG WHERE LOAIPHONG=NLOAIPHONG;
	ELSEIF NLOAIPHONG IS NULL
	THEN   
			SELECT * FROM PHONG WHERE TINHTRANG=NTINHTRANG;
	ELSE
		SELECT * FROM PHONG WHERE LOAIPHONG=NLOAIPHONG AND TINHTRANG=NTINHTRANG;
    END IF;
End $$
DELIMITER ;
CALL XEM_DS_PHONG_THEO_DK('PHONG DON',NULL);