USE `DA_PTTK`;

-- KHACH HANG DANG KY TAI KHOAN
DELIMITER $$  
drop procedure if exists DANG_KY_KHACHHANG;
CREATE PROCEDURE DANG_KY_KHACHHANG(
	IN NTENKH varchar(50) ,
	IN NSDT varchar(5) ,
	IN NEMAIL varchar(50) , 
	IN NMAHOCHIEU varchar(5) ,
	IN NCMND varchar(5))
BEGIN
	IF NCMND IN (SELECT CMND FROM KHACHHANG)
    THEN
		SELECT 'KHACH HANG DA TON TAI' AS '';
        ROLLBACK;
	ELSE
		CALL THEM_KHACHHANG(NTENKH, NULL, NSDT, NEMAIL, NULL, NULL, NULL, '0', NMAHOCHIEU, NCMND, NULL, NULL, @NMAKH);
		IF @NMAKH IS NULL
		THEN
			SELECT 'DANG KI THAT BAI' AS '';
			ROLLBACK;
		ELSE 
			SELECT @NMAKH;
		END IF;
	END IF;
End $$
DELIMITER ;
CALL DANG_KY_KHACHHANG('PHUONG', '11111', 'EMAIL','HC','CMND');
