USE `DA_PTTK`;

-- XEM DS PHIEUDAT TINHTRANG DA DAT
DELIMITER $$  
drop procedure if exists XEM_DS_PHIEUDAT_TINHTRANG_DADAT;
CREATE PROCEDURE XEM_DS_PHIEUDAT_TINHTRANG_DADAT()
BEGIN
	SELECT * FROM PHIEUDATPHONG WHERE TINHTRANG='DA DAT';
End $$
DELIMITER ;

CALL XEM_DS_PHIEUDAT_TINHTRANG_DADAT();

-- XEM DS PHIEUDAT BAT DAU HOM NAY
DELIMITER $$  
drop procedure if exists XEM_PHIEUDAT_HOMNAY;
CREATE PROCEDURE XEM_PHIEUDAT_HOMNAY()
BEGIN
	SELECT * FROM CHITIETPHIEUDAT WHERE TGBATDAU=CURDATE();
End $$
DELIMITER ;
CALL XEM_PHIEUDAT_HOMNAY;

-- XEM LICH SU PHIEU DAT CUA KHACH HANG
DELIMITER $$  
drop procedure if exists XEM_LS_PDP_KH;
CREATE PROCEDURE XEM_LS_PDP_KH(IN NMAKH VARCHAR(5))
BEGIN
	SELECT * FROM PHIEUDATPHONG WHERE MAKH=NMAKH;
End $$
DELIMITER ;
CALL XEM_LS_PDP_KH('KH001');

-- XEM DS CHI TIET PHIEU DAT
DELIMITER $$  
drop procedure if exists XEM_DS_CHITIETPHIEUDAT_THEO_MAPDP;
CREATE PROCEDURE XEM_DS_CHITIETPHIEUDAT_THEO_MAPDP(IN NMAPDP VARCHAR(5))
BEGIN
	SELECT * FROM CHITIETPHIEUDAT WHERE MAPDP=NMAPDP;
End $$
DELIMITER ;

CALL XEM_DS_CHITIETPHIEUDAT_THEO_MAPDP('DP001');