-- CHINH LAI DICHVUCUAPHONG

DELETE FROM DICHVUCUAPHONG WHERE MADV='DV1';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV2';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV3';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV4';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV5';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV6';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV7';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV8';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV9';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV10';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV11';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV12';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV13';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV14';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV15';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV16';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV17';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV18';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV19';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV20';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV21';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV22';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV23';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV24';
DELETE FROM DICHVUCUAPHONG WHERE MADV='DV25';