-- XEM THONG TIN SAN PHAM
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_TT_SANPHAM;
CREATE PROCEDURE XEM_TT_SANPHAM(
    IN NMASP VARCHAR(5)
)
BEGIN
	IF NMASP NOT IN (SELECT MASP FROM SANPHAM)
    THEN   
		BEGIN 
			SELECT 'SAN PHAM KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE 
		BEGIN
		SELECT *
		FROM SANPHAM
		WHERE MASP = NMASP;
        END;
	END IF;
END$$

DELIMITER ;
CALL XEM_TT_SANPHAM('SP010');
SELECT * FROM NHANVIEN
-- ----------------------------------------------------------------------------------------------------
-- kiem tra nguoi dung
DELIMITER $$
-- DROP PROCEDURE IF EXISTS KT_NGUOIDUNG;
CREATE PROCEDURE KT_NGUOIDUNG(IN NMA VARCHAR(5) CHARACTER SET utf8mb4, OUT MESS VARCHAR(5))
BEGIN
	IF NMA IN (SELECT MAKH FROM KHACHHANG)
	THEN   
		BEGIN 
			SET MESS = '1';
        END;
	ELSEIF NMA IN (SELECT MANV FROM NHANVIEN WHERE MANV LIKE 'LT%')
    THEN
		BEGIN
			SET MESS ='2';
        END;
	ELSE
		BEGIN
			SET MESS = '0';
		END;
		END IF;
END$$
DELIMITER ;


-- XEM THONG TIN KHACH HANG
DELIMITER $$
-- DROP PROCEDURE IF EXISTS XEM_TT_KHACHHANG;
CREATE PROCEDURE XEM_TT_KHACHHANG(IN NMAKH VARCHAR(5) CHARACTER SET utf8mb4)
BEGIN
	IF NMAKH NOT IN (SELECT MAKH FROM KHACHHANG)
	THEN   
		BEGIN 
			SELECT 'KHACH HANG KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
	SELECT * FROM KHACHHANG WHERE MAKH=NMAKH;
    END IF;
END$$
DELIMITER ;
CALL XEM_TT_KHACHHANG('KH001');
-- ----------------------------------------------------------------------------------------------------
-- XEM THONG TIN PHONG
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_TT_PHONG;
CREATE PROCEDURE XEM_TT_PHONG(IN NMAPHONG VARCHAR(5))
BEGIN
	IF NMAPHONG NOT IN (SELECT MAPHONG FROM PHONG)
	THEN   
		BEGIN 
			SELECT 'PHONG KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
	SELECT * FROM PHONG WHERE MAPHONG=NMAPHONG;
    END IF;
END$$
DELIMITER ;
CALL XEM_TT_PHONG('P000');
-- ----------------------------------------------------------------------------------------------------
-- XEM THONG TIN DICH VU LU HANH
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_TT_DICHVULUHANH;
CREATE PROCEDURE XEM_TT_DICHVULUHANH(IN NMADV VARCHAR(5))
BEGIN
	IF NMADV NOT IN (SELECT MADV FROM DICHVULUHANH)
	THEN   
		BEGIN 
			SELECT 'DICH VU KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
	SELECT * FROM DICHVULUHANH WHERE MADV=NMADV;
    END IF;
END$$
DELIMITER ;
CALL XEM_TT_DICHVULUHANH('LH001');
-- ----------------------------------------------------------------------------------------------------
-- XEM THONG TIN DICH VU KHACH SAN
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_TT_DICHVUKHACHSAN;
CREATE PROCEDURE XEM_TT_DICHVUKHACHSAN(IN NMADV VARCHAR(5))
BEGIN
	IF NMADV NOT IN (SELECT MADV FROM DICHVUKHACHSAN)
	THEN   
		BEGIN 
			SELECT 'DICH VU KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
	SELECT * FROM DICHVUKHACHSAN WHERE MADV=NMADV;
    END IF;
END$$
DELIMITER ;
CALL XEM_TT_DICHVUKHACHSAN('DV001');
-- ----------------------------------------------------------------------------------------------------
-- XEM THONG TIN DOI TAC LU HANH
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_TT_DOITACLUHANH;
CREATE PROCEDURE XEM_TT_DOITACLUHANH(IN NMADT VARCHAR(5))
BEGIN
	IF NMADT NOT IN (SELECT MADT FROM DOITACLUHANH)
	THEN   
		BEGIN 
			SELECT 'DOI TAC KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
	SELECT * FROM DOITACLUHANH WHERE MADT=NMADT;
    END IF;
END$$
DELIMITER ;
CALL XEM_TT_DOITACLUHANH('DT001');
-- ----------------------------------------------------------------------------------------------------
-- XEM THONG TIN NHAN VIEN
DELIMITER $$
-- DROP PROCEDURE IF EXISTS XEM_TT_NHANVIEN;
CREATE PROCEDURE XEM_TT_NHANVIEN(IN NMANV VARCHAR(5) CHARACTER SET utf8mb4)
BEGIN
	IF NMANV NOT IN (SELECT MANV FROM NHANVIEN)
	THEN   
		BEGIN 
			SELECT 'NHAN VIEN KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
	SELECT * FROM NHANVIEN WHERE MANV = NMANV;
    END IF;
END$$
DELIMITER ;
CALL XEM_TT_NHANVIEN('LT001');
-- ----------------------------------------------------------------------------------------------------
-- XEM THONG TIN DOAN
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_TT_DOAN;
CREATE PROCEDURE XEM_TT_DOAN(IN NMADOAN VARCHAR(5))
BEGIN
	IF NMADOAN NOT IN (SELECT MADOAN FROM DOAN)
	THEN   
		BEGIN 
			SELECT 'DOAN KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
	SELECT * FROM DOAN WHERE MADOAN=NMADOAN;
    END IF;
END$$
DELIMITER ;
CALL XEM_TT_DOAN('D0001');
-- ----------------------------------------------------------------------------------------------------
-- XEM THONG TIN PHIEU SU DUNG
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_TT_PHIEUSUDUNG;
CREATE PROCEDURE XEM_TT_PHIEUSUDUNG(IN NMAPHIEUSD VARCHAR(5))
BEGIN
	IF NMAPHIEUSD NOT IN (SELECT MAPHIEUSD FROM PHIEUSUDUNG)
	THEN   
		BEGIN 
			SELECT 'PHIEU SU DUNG KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
	SELECT * FROM PHIEUSUDUNG WHERE MAPHIEUSD=NMAPHIEUSD;
    END IF;
END$$
DELIMITER ;
CALL XEM_TT_PHIEUSUDUNG('PSD01');
-- ----------------------------------------------------------------------------------------------------
-- XEM THONG TIN PHIEU DAT PHONG
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_TT_PHIEUDATPHONG;
CREATE PROCEDURE XEM_TT_PHIEUDATPHONG(IN NMAPDP VARCHAR(5))
BEGIN
	IF NMAPDP NOT IN (SELECT MAPDP FROM PHIEUDATPHONG)
	THEN   
		BEGIN 
			SELECT 'PHIEU DAT PHONG KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
	SELECT * FROM PHIEUDATPHONG WHERE MAPDP=NMAPDP;
    END IF;
END$$
DELIMITER ;
CALL XEM_TT_PHIEUDATPHONG('DP001');
-- ----------------------------------------------------------------------------------------------------
-- XEM TT PHIEU DANG KY NHAN PHONG
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_TT_PHIEUDANGKYNHANPHONG;
CREATE PROCEDURE XEM_TT_PHIEUDANGKYNHANPHONG(IN NMACTPD VARCHAR(5))
BEGIN
	IF NMACTPD NOT IN (SELECT MACTPD FROM PHIEUDANGKYNHANPHONG)
	THEN   
		BEGIN 
			SELECT 'PHIEU DANG KY NHAN PHONG KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
	SELECT * FROM PHIEUDANGKYNHANPHONG WHERE MACTPD=NMACTPD;
    END IF;
END$$
DELIMITER ;
CALL XEM_TT_PHIEUDANGKYNHANPHONG('PDK01');
-- ----------------------------------------------------------------------------------------------------
-- XEM TT HANH LY
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_TT_HANHLY;
CREATE PROCEDURE XEM_TT_HANHLY(IN NMAHANHLY VARCHAR(5))
BEGIN
	IF NMAHANHLY NOT IN (SELECT MAHANHLY FROM HANHLY)
	THEN   
		BEGIN 
			SELECT 'HANH LY KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
	SELECT * FROM HANHLY WHERE MAHANHLY=NMAHANHLY;
    END IF;
END$$
DELIMITER ;
CALL XEM_TT_HANHLY('HL001');
-- ----------------------------------------------------------------------------------------------------
-- XEM TT DAI LY TRUNG GIAN
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_TT_DAILYTRUNGGIAN;
CREATE PROCEDURE XEM_TT_DAILYTRUNGGIAN(IN NMADLTG VARCHAR(5))
BEGIN
	IF NMADLTG NOT IN (SELECT MADLTG FROM DAILYTRUNGGIAN)
	THEN   
		BEGIN 
			SELECT 'DAI LY KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
	SELECT * FROM DAILYTRUNGGIAN WHERE MADLTG=NMADLTG;
    END IF;
END$$
DELIMITER ;
CALL XEM_TT_DAILYTRUNGGIAN('DL001');
-- ----------------------------------------------------------------------------------------------------
-- XEM TT CHI TIET HOA DON
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_TT_CHITIETHOADON;
CREATE PROCEDURE XEM_TT_CHITIETHOADON(IN NMAHD VARCHAR(5))
BEGIN
	IF NMAHD NOT IN (SELECT MAHD FROM CHITIETHOADON)
	THEN   
		BEGIN 
			SELECT 'HOA DON KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
	SELECT * FROM CHITIETHOADON WHERE MAHD=NMAHD;
    END IF;
END$$
DELIMITER ;
CALL XEM_TT_CHITIETHOADON('HD1');
-- ----------------------------------------------------------------------------------------------------
-- XEM TT CHI TIET PHIEU DAT
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_TT_CHITIETPHIEUDAT;
CREATE PROCEDURE XEM_TT_CHITIETPHIEUDAT(IN NMACTPD VARCHAR(10))
BEGIN
	IF NMACTPD NOT IN (SELECT MACTPD FROM CHITIETPHIEUDAT)
	THEN   
		BEGIN 
			SELECT 'CHI TIET KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
	SELECT * FROM CHITIETPHIEUDAT WHERE MACTPD=NMACTPD;
    END IF;
END$$
DELIMITER ;
CALL XEM_TT_CHITIETPHIEUDAT('CTPD1');
-- ----------------------------------------------------------------------------------------------------
-- XEM TT HOA DON
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_TT_HOADON;
CREATE PROCEDURE XEM_TT_HOADON(IN NMAHD VARCHAR(10))
BEGIN
	IF NMAHD NOT IN (SELECT MAHD FROM HOADON)
	THEN   
		BEGIN 
			SELECT 'HOA DON KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
	SELECT * FROM HOADON WHERE MAHD=NMAHD;
    END IF;
END$$
DELIMITER ;
CALL XEM_TT_HOADON('HD1');
-- ----------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------
-- KHACH HANG DANG KY TAI KHOAN
DELIMITER $$  
--  drop procedure if exists DANG_KY_KHACHHANG;
CREATE PROCEDURE DANG_KY_KHACHHANG(
	IN NTENKH varchar(50) CHARACTER SET utf8mb4,
	IN NSDT varchar(5) CHARACTER SET utf8mb4,
	IN NEMAIL varchar(50) CHARACTER SET utf8mb4, 
	IN NMAHOCHIEU varchar(5) CHARACTER SET utf8mb4,
	IN NCMND varchar(5) CHARACTER SET utf8mb4,
    OUT MESS VARCHAR(100))
BEGIN
	IF NCMND IN (SELECT CMND FROM KHACHHANG)
    THEN
		SET MESS = 'KHACH HANG DA TON TAI';
        ROLLBACK;
	ELSE
		CALL THEM_KHACHHANG(NTENKH, NULL, NSDT, NEMAIL, NULL, NULL, NULL, '0', NMAHOCHIEU, NCMND, NULL, NULL, @NMAKH);
		IF @NMAKH IS NULL
		THEN
			SET MESS = 'DANG KI THAT BAI';
			ROLLBACK;
		ELSE 
			SET MESS = @NMAKH;
		END IF;
	END IF;
End $$
DELIMITER ;
CALL DANG_KY_KHACHHANG('PHUONG', '11111', 'EMAIL','HC','CMND');

DELIMITER $$  
-- drop procedure if exists XEM_DS_PHIEUDATPHONG_THEO_MAKH;
CREATE PROCEDURE XEM_DS_PHIEUDATPHONG_THEO_MAKH(IN NMAKH VARCHAR(5) CHARACTER SET utf8mb4)
BEGIN
	SELECT * FROM PHIEUDATPHONG WHERE MAKH=NMAKH;
End $$
DELIMITER ;
CALL XEM_DS_PHIEUDATPHONG_THEO_MAKH('KH004');


DELIMITER $$  
-- drop procedure if exists XEM_DS_CHITIETPHIEUDAT_THEO_MAPDP;
CREATE PROCEDURE XEM_DS_CHITIETPHIEUDAT_THEO_MAPDP(IN NMAPDP VARCHAR(5) CHARACTER SET utf8mb4)
BEGIN
	SELECT * FROM CHITIETPHIEUDAT WHERE MAPDP=NMAPDP;
End $$
DELIMITER ;

CALL XEM_DS_CHITIETPHIEUDAT_THEO_MAPDP('DP001');

DELIMITER $$  
-- drop procedure if exists XEM_DS_DV_CUA_PDP;
CREATE PROCEDURE XEM_DS_DV_CUA_PDP(IN NMAPDP VARCHAR(5) CHARACTER SET utf8mb4)
BEGIN
	SELECT DISTINCT DVP.* FROM PHIEUDATPHONG PDP, CHITIETPHIEUDAT CTPD, DICHVUCUAPHONG DVP WHERE PDP.MAPDP= NMAPDP AND CTPD.MAPDP= PDP.MAPDP AND DVP.MAPHONG = CTPD.MAPHONG;
End $$
DELIMITER ;
select * from HOADON;
CALL XEM_DS_DV_CUA_PDP('DP001');



DELIMITER $$  
-- drop procedure if exists XEM_DS_HD_CUA_KH;
CREATE PROCEDURE XEM_DS_HD_CUA_KH(IN NMAKH VARCHAR(5) CHARACTER SET utf8mb4)
BEGIN
	SELECT * FROM HOADON WHERE MAKH = NMAKH;
End $$
DELIMITER ;

DELIMITER $$  
-- drop procedure if exists XEM_DS_PHONG_THEO_DK;
CREATE PROCEDURE XEM_DS_PHONG_THEO_DK(IN NLOAIPHONG VARCHAR(20) CHARACTER SET utf8mb4, IN NTINHTRANG VARCHAR(20) CHARACTER SET utf8mb4)
BEGIN
	IF NLOAIPHONG IS NULL AND NTINHTRANG IS NULL
    THEN
		SELECT * FROM PHONG;
	ELSEIF NTINHTRANG IS NULL
	THEN   
		SELECT * FROM PHONG WHERE LOAIPHONG=NLOAIPHONG;
	ELSEIF NLOAIPHONG IS NULL
	THEN   
			SELECT * FROM PHONG WHERE TINHTRANG=NTINHTRANG;
	ELSE
		SELECT * FROM PHONG WHERE LOAIPHONG=NLOAIPHONG AND TINHTRANG=NTINHTRANG;
    END IF;
End $$
DELIMITER ;
CALL XEM_DS_PHONG_THEO_DK('PHONG DON',NULL);


DELIMITER $$  
-- drop procedure if exists XEM_DS_PHONG_THEO_DK_1;
CREATE PROCEDURE XEM_DS_PHONG_THEO_DK_1(IN NLOAIPHONG VARCHAR(20) CHARACTER SET utf8mb4, IN NTINHTRANG VARCHAR(20) CHARACTER SET utf8mb4)
BEGIN
	IF NLOAIPHONG = 'NULL' AND NTINHTRANG = 'NULL'
    THEN
		SELECT * FROM PHONG;
	ELSEIF NTINHTRANG = 'NULL'
	THEN   
		SELECT * FROM PHONG WHERE LOAIPHONG=NLOAIPHONG;
	ELSEIF NLOAIPHONG = 'NULL'
	THEN   
			SELECT * FROM PHONG WHERE TINHTRANG=NTINHTRANG;
	ELSE
		SELECT * FROM PHONG WHERE LOAIPHONG=NLOAIPHONG AND TINHTRANG=NTINHTRANG;
    END IF;
End $$
DELIMITER ;
CALL XEM_DS_PHONG_THEO_DK('PHONG DON',NULL);