-- CHINH SUA THONG TIN SAN PHAM
DELIMITER $$
DROP PROCEDURE IF EXISTS CHINHSUA_TT_SANPHAM;
CREATE PROCEDURE CHINHSUA_TT_SANPHAM(
    IN NMASP VARCHAR(5),
    IN NTENSP VARCHAR(50),
    IN NGIA FLOAT
)
BEGIN
    IF NMASP NOT IN (SELECT MASP FROM SANPHAM)
    THEN
        SELECT 'SAN PHAM KHONG TON TAI' AS '';
    ELSE
        UPDATE SANPHAM SET TENSP = NTENSP, GIA = NGIA WHERE MASP = NMASP;
        SELECT 'THANH CONG' AS '';
    END IF;
END$$
DELIMITER ;

CALL CHINHSUA_TT_SANPHAM('SP010', 'KEM', '20000');
-- ----------------------------------------------------------------------------------------------------
-- CHINH SUA THONG TIN KHACH HANG
DELIMITER $$
DROP PROCEDURE IF EXISTS CHINHSUA_TT_KHACHHANG;
CREATE PROCEDURE CHINHSUA_TT_KHACHHANG(IN NMAKH VARCHAR(5), IN NTENKH VARCHAR(50), IN NDIACHI VARCHAR(50), IN NSDT VARCHAR(5), IN NEMAIL VARCHAR(5), IN NMADLTG VARCHAR(5), IN NMADOAN VARCHAR(5) )
BEGIN
	IF NMAKH NOT IN (SELECT MAKH FROM KHACHHANG)
	THEN   
		BEGIN 
			SELECT 'KHACH HANG KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSEIF NMADLTG NOT IN (SELECT MADLTG FROM DAILYTRUNGGIAN)
	THEN
		BEGIN 
			SELECT 'DAI LY KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSEIF NMADOAN NOT IN (SELECT MADOAN FROM DOAN)
	THEN
		BEGIN 
			SELECT 'DOI TAC KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
		BEGIN
		UPDATE KHACHHANG SET	TENKH=NTENKH,
								DIACHI=NDIACHI,
                                SDT=NSDT,
                                EMAIL=NEMAIL,
                                MADLTG=NMADLTG,
                                MADOAN=NMADOAN
						WHERE MAKH=NMAKH;
		SELECT 'THANH CONG' AS '';
        END;
        END IF;
END$$
DELIMITER ;
CALL CHINHSUA_TT_KHACHHANG('KH021', 'A','A','A','A','DL001','D0001');
-- ----------------------------------------------------------------------------------------------------
-- CHINH SUA THONG TIN PHONG
DELIMITER $$
DROP PROCEDURE IF EXISTS CHINHSUA_TT_PHONG;
CREATE PROCEDURE CHINHSUA_TT_PHONG(IN NMAPHONG VARCHAR(5), IN NTINHTRANG VARCHAR(20), IN NLOAIPHONG VARCHAR(50), IN NCANDONPHONG VARCHAR(5), IN NGIAPHONG FLOAT, IN NTANG INT )
BEGIN
	IF NMAPHONG NOT IN (SELECT MAPHONG FROM PHONG)
	THEN   
		BEGIN 
			SELECT 'PHONG KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSEIF NGIAPHONG <0
	THEN
		BEGIN 
			SELECT 'GIA PHONG PHAI LON HON 0' AS '';
			ROLLBACK;
        END;
	ELSEIF NTANG NOT IN (1,2,3)
	THEN
		BEGIN 
			SELECT 'TANG KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
		BEGIN
		UPDATE PHONG SET	TINHTRANG=NTINHTRANG,
							LOAIPHONG=NLOAIPHONG,
							CANDONPHONG=NCANDONPHONG,
							GIAPHONG=NGIAPHONG,
							TANG=NTANG
						WHERE MAPHONG=NMAPHONG;
		SELECT 'THANH CONG' AS '';
        END;
        END IF;
END$$
DELIMITER ;
CALL CHINHSUA_TT_PHONG('P0001', 'DA DAT', 'PHONG DON', '0', '200000', '1');
-- ----------------------------------------------------------------------------------------------------
-- CHINH SUA DICH VU LU HANH
DELIMITER $$
DROP PROCEDURE IF EXISTS CHINHSUA_TT_DICHVULUHANH;
CREATE PROCEDURE CHINHSUA_TT_DICHVULUHANH(IN NMADV VARCHAR(5), IN NTENDV VARCHAR(50), IN NDIADIEM VARCHAR(50), IN NSONGAY INT, IN NMADT VARCHAR(5))
BEGIN
	IF NMADV NOT IN (SELECT MADV FROM DICHVULUHANH)
	THEN   
		BEGIN 
			SELECT 'DICH VU KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSEIF NSONGAY <-1
	THEN
		BEGIN 
			SELECT 'SO NGAY PHAI LON HON 0' AS '';
			ROLLBACK;
        END;
	ELSEIF NMADT NOT IN (SELECT MADT FROM DOITACLUHANH)
	THEN
		BEGIN 
			SELECT 'DOI TAC KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
		BEGIN
		UPDATE DICHVULUHANH SET	TENDV=NTENDV,
								DIADIEM=NDIADIEM,
								SONGAY=NSONGAY,
								MADT=NMADT
						WHERE MADV=NMADV;
		SELECT 'THANH CONG' AS '';
        END;
        END IF;
END$$
DELIMITER ;
CALL CHINHSUA_TT_DICHVULUHANH('LH001', 'A', 'A', 1, 'DT001');
-- ----------------------------------------------------------------------------------------------------
-- CHINH SUA DICH VU KHACH SAN
DELIMITER $$
DROP PROCEDURE IF EXISTS CHINHSUA_TT_DICHVUKHACHSAN;
CREATE PROCEDURE CHINHSUA_TT_DICHVUKHACHSAN(IN NMADV VARCHAR(5), IN NTENDV VARCHAR(50), IN NGIA FLOAT, IN NSLMAX INT, IN NTINHTRANG VARCHAR(20))
BEGIN
	IF NMADV NOT IN (SELECT MADV FROM DICHVUKHACHSAN)
	THEN   
		BEGIN 
			SELECT 'DICH VU KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSEIF NGIA < 0
	THEN
		BEGIN 
			SELECT 'GIA DICH VU PHAI LON HON 0' AS '';
			ROLLBACK;
        END;
	ELSEIF NSLMAX < 0
	THEN
		BEGIN 
			SELECT 'SO LUONG PHAI LON HON 0' AS '';
			ROLLBACK;
        END;
	ELSE
		BEGIN
		UPDATE DICHVUKHACHSAN SET	TENDV=NTENDV,
								GIA=NGIA,
                                SLMAX=NSLMAX,
                                TINHTRANG=NTINHTRANG
						WHERE MADV=NMADV;
		SELECT 'THANH CONG' AS '';
        END;
	END IF;
END$$
DELIMITER ;
CALL CHINHSUA_TT_DICHVUKHACHSAN('DV001', 'A',1,1,'A');
-- ----------------------------------------------------------------------------------------------------
-- CHINH SUA THONG TIN DOI TAC LU HANH
DELIMITER $$
DROP PROCEDURE IF EXISTS CHINHSUA_TT_DOITACLUHANH;
CREATE PROCEDURE CHINHSUA_TT_DOITACLUHANH(IN NMADT VARCHAR(5), IN NTENDT VARCHAR(50), IN NSDT VARCHAR(10), IN NDIACHI VARCHAR(50), IN NEMAIL VARCHAR(20), IN NNGAYHOPTAC DATE)
BEGIN
	IF NMADT NOT IN (SELECT MADT FROM DOITACLUHANH)
	THEN   
		BEGIN 
			SELECT 'DOI TAC KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
		BEGIN
		UPDATE DOITACLUHANH SET	TENDT = NTENDT,
								SDT = NSDT,
                                DIACHI = NDIACHI,
                                EMAIL = NEMAIL,
                                NGAYHOPTAC = NNGAYHOPTAC
						WHERE MADT=NMADT;
		SELECT 'THANH CONG' AS '';
        END;
	END IF;
END$$
DELIMITER ;
CALL CHINHSUA_TT_DOITACLUHANH('DT001', 'A','1','1','A',DATE('2023-03-03'));
-- ----------------------------------------------------------------------------------------------------
-- SUA THONG TIN NHAN VIEN
DELIMITER $$
DROP PROCEDURE IF EXISTS CHINHSUA_TT_NHANIEN;
CREATE PROCEDURE CHINHSUA_TT_NHANIEN(IN NMANV VARCHAR(5), IN NTENNV VARCHAR(50), IN NSDT VARCHAR(5), IN NCHUCVU VARCHAR(20), IN NLUONG FLOAT)
BEGIN
	IF NMANV NOT IN (SELECT MANV FROM NHANVIEN)
	THEN   
		BEGIN 
			SELECT 'NHAN VIEN KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
		BEGIN
		UPDATE NHANVIEN SET	TENNV = NTENNV,
							SDT = NSDT,
							CHUCVU = NCHUCVU,
							LUONG = NLUONG
						WHERE MANV = NMANV;
		SELECT 'THANH CONG' AS '';
        END;
	END IF;
END$$
DELIMITER ;
CALL CHINHSUA_TT_NHANIEN('KT001', 'KE TOAN 1','00143', 'KE TOAN', '5000100');
-- ----------------------------------------------------------------------------------------------------
-- CHINH SUA THONG TIN DOAN
DELIMITER $$
DROP PROCEDURE IF EXISTS CHINHSUA_TT_DOAN; 
CREATE PROCEDURE CHINHSUA_TT_DOAN(IN NMADOAN VARCHAR(5), IN NTENDOAN VARCHAR(20), IN NSLKHACH FLOAT, IN NNGAYDEN DATE, IN NSODEMLUUTRU INT, IN NMADLTG VARCHAR(5))
BEGIN
	IF NMADOAN NOT IN (SELECT MADOAN FROM DOAN)
	THEN   
		BEGIN 
			SELECT 'DOAN KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSEIF NMADLTG NOT IN (SELECT MADLTG FROM DAILYTRUNGGIAN)
    THEN
		BEGIN
			SELECT 'DAI LY KHONG TON TAI' AS '';
            ROLLBACK;
		END;
	ELSE
	BEGIN
	UPDATE DOAN SET	TENDOAN = NTENDOAN,
					SLKHACH = NSLKHACH,
					NGAYDEN = NNGAYDEN,
					SODEMLUUTRU = NSODEMLUUTRU,
					MADLTG = NMADLTG
				WHERE MADOAN = NMADOAN;
	SELECT 'THANH CONG' AS '';
    END;
    END IF;
END$$
DELIMITER ;
CALL CHINHSUA_TT_DOAN('D0010','DM',1,DATE('2023-03-03'),1,'DL001');
-- ----------------------------------------------------------------------------------------------------
-- CHINH SUA THONG TIN PHIEU SU DUNG
DELIMITER $$
DROP PROCEDURE IF EXISTS CHINHSUA_TT_PHIEUSUDUNG; 
CREATE PROCEDURE CHINHSUA_TT_PHIEUSUDUNG(
	IN NMAPHIEUSD VARCHAR(5), IN NMAPHONG VARCHAR(5), IN NMANV VARCHAR(5), IN NMADV VARCHAR(5), IN NMASP VARCHAR(5), IN NNGAYDANGKY DATE, IN NGIA FLOAT, IN NSOLUONG INT)
BEGIN
	IF NMAPHIEUSD NOT IN (SELECT MAPHIEUSD FROM PHIEUSUDUNG)
	THEN   
		BEGIN 
			SELECT 'PHIEU SU DUNG KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSEIF NMAPHONG NOT IN (SELECT MAPHONG FROM PHONG)
    THEN
		BEGIN
			SELECT 'PHONG KHONG TON TAI' AS '';
            ROLLBACK;
		END;
	ELSEIF NMANV NOT IN (SELECT MANV FROM NHANVIEN)
    THEN
		BEGIN
			SELECT 'NHAN VIEN LAP PHIEU KHONG TON TAI' AS '';
            ROLLBACK;
		END;
	ELSEIF NMADV NOT IN (SELECT MADV FROM DICHVUKHACHSAN) AND NMADV NOT NULL
    THEN
		BEGIN
			SELECT 'NHAN VIEN LAP PHIEU KHONG TON TAI' AS '';
            ROLLBACK;
		END;
	ELSE
	BEGIN
	UPDATE DOAN SET	TENDOAN = NTENDOAN,
					SLKHACH = NSLKHACH,
					NGAYDEN = NNGAYDEN,
					SODEMLUUTRU = NSODEMLUUTRU,
					MADLTG = NMADLTG
				WHERE MADOAN = NMADOAN;
	SELECT 'THANH CONG' AS '';
    END;
    END IF;
END$$
DELIMITER ;
CALL CHINHSUA_TT_PHIEUSUDUNG('D0010','DM',1,DATE('2023-03-03'),1,'DL001');
-- ----------------------------------------------------------------------------------------------------
-- CHINH SUA PHIEU DAT PHONG
DELIMITER $$
DROP PROCEDURE IF EXISTS CHINHSUA_TT_PHIEUDATPHONG;
CREATE PROCEDURE CHINHSUA_TT_PHIEUDATPHONG (
	IN NMAPDP VARCHAR(5),
	IN NNGAYDAT DATE,
    IN NYEUCAU  VARCHAR(50),
    IN NSLPHONG INT,
    IN NMADLTG VARCHAR(5),
    IN NMAKH VARCHAR(5),
    IN NMANV VARCHAR(5)
)
BEGIN
	IF NMAPDP NOT IN (SELECT MAPDP FROM PHIEUDATPHONG)
	THEN   
		BEGIN 
			SELECT 'PHIEU DAT PHONG KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSEIF NMAKH NOT IN (SELECT MAKH FROM KHACHHANG)
	THEN 
        BEGIN 
            SELECT 'KHACH HANG KHONG TON TAI' AS '';
            ROLLBACK;
        END;
    ELSEIF NMANV NOT IN (SELECT MANV FROM NHANVIEN)
    THEN
        BEGIN 
            SELECT 'NHAN VIEN KHONG TON TAI' AS '';
            ROLLBACK;
        END;
    ELSEIF NMADLTG NOT IN (SELECT MADLTG FROM DAILYTRUNGGIAN)
    THEN
        BEGIN 
            SELECT 'DAI LY TRUNG GIAN KHONG TON TAI' AS '';
            ROLLBACK;
        END;
    ELSE 
		BEGIN
			UPDATE PHIEUDATPHONG SET
				NGAYDAT = NNGAYDAT,
				YEUCAU = NYEUCAU,
				SLPHONG = NSLPHONG,
				MADLTG = NMADLTG,
				MAKH = NMAKH,
				MANV = NMANV
			WHERE MAPDP = NMAPDP;
			SELECT 'THANH CONG' AS '';
			COMMIT;
		END;
    END IF;
END$$
DELIMITER ;
CALL CHINHSUA_TT_PHIEUDATPHONG('DP010', '2023-10-03', 'PHONG CO BAN CONG', 2, 'DL001', 'KH009', 'LT004');
-- ----------------------------------------------------------------------------------------------------
-- CHINH SUA PHIEU DANG KY NHAN PHONG
DELIMITER $$
DROP PROCEDURE IF EXISTS CHINHSUA_TT_PHIEUDANGKYNHANPHONG; 
CREATE PROCEDURE CHINHSUA_TT_PHIEUDANGKYNHANPHONG(
	IN 	NMACTPD varchar(5),
		NTINHTRANG varchar(20),
		NSLTHIEU int, 
		NSLHANHLY int, 
		NYEUCAUDACBIET varchar(50), 
		NDANHGIA varchar(50), 
		NMANVLETAN varchar(5), 
		NMANVBELLMAN varchar(5), 
		NMAPDP varchar(5))
BEGIN
	IF NMACTPD NOT IN (SELECT MACTPD FROM PHIEUDANGKYNHANPHONG)
    THEN
		BEGIN
			SELECT 'MA DANG KY KHONG TON TAI' AS '';
            ROLLBACK;
        END;
	ELSEIF NMANVLETAN NOT IN (SELECT MANV FROM NHANVIEN) OR NMANVLETAN NOT LIKE 'LT%' OR NMANVLETAN IS NULL
	THEN   
		BEGIN 
			SELECT 'MA LE TAN KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSEIF NMANVBELLMAN NOT IN (SELECT MANV FROM NHANVIEN) OR NMANVBELLMAN NOT LIKE 'BM%'OR NMANVBELLMAN IS NULL
    THEN
		BEGIN
			SELECT 'MA NV BELLMAN KHONG TON TAI' AS '';
            ROLLBACK;
		END;
	ELSEIF NSLHANHLY <1
    THEN
		BEGIN
			SELECT 'SO LUONG HANH LY PHAI LON HON 0' AS '';
            ROLLBACK;
		END;
	ELSEIF NMAPDP NOT IN (SELECT MAPDP FROM PHIEUDATPHONG) OR NMAPDP IS NULL
    THEN
		BEGIN
			SELECT 'PHIEU DAT PHONG KHONG TON TAI' AS '';
            ROLLBACK;
		END;
	ELSE
	BEGIN
	UPDATE PHIEUDANGKYNHANPHONG SET	
		TINHTRANG = NTINHTRANG,
		SLTHIEU = NSLTHIEU,
		SLHANHLY =NSLHANHLY, 
		YEUCAUDACBIET = NYEUCAUDACBIET,
		DANHGIA = NDANHGIA,
		MANVLETAN = NMANVLETAN,
		MANVBELLMAN = NMANVBELLMAN
				WHERE MACTPD= NMACTPD ;
	SELECT 'THANH CONG' AS '';
    END;
    END IF;
END$$
DELIMITER ;
SELECT * FROM NHANVIEN;
CALL CHINHSUA_TT_PHIEUDANGKYNHANPHONG('PK01','A',1,1,'1','1','LT001', 'BM001','DP001');
-- ----------------------------------------------------------------------------------------------------
-- CHINH SUA THONG TIN HANH LY
DELIMITER $$
DROP PROCEDURE IF EXISTS CHINHSUA_TT_HANHLY; 
CREATE PROCEDURE CHINHSUA_TT_HANHLY(NMAHANHLY varchar(5),
									NMAU varchar(10) ,
									NTINHTRANGVANCHUYEN varchar(20), 
									NMAKH varchar(5) ,
									NMACTPD varchar(10))
BEGIN
	IF NMAHANHLY NOT IN (SELECT MAHANHLY FROM HANHLY) OR NMAHANHLY IS NULL
	THEN   
		BEGIN 
			SELECT 'HANH LY KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSEIF NMAKH NOT IN (SELECT MAKH FROM KHACHHANG) OR NMAKH IS NULL
    THEN
		BEGIN
			SELECT 'KHACH HANG KHONG TON TAI' AS '';
            ROLLBACK;
		END;
	ELSEIF NMACTPD NOT IN (SELECT MACTPD FROM CHITIETPHIEUDAT) OR NMACTPD IS NULL
    THEN
		BEGIN
			SELECT 'PHIEU DAT KHONG TON TAI' AS '';
            ROLLBACK;
		END;
	ELSE
	BEGIN
	UPDATE HANHLY SET	MAU=NMAU,
						TINHTRANGVANCHUYEN=NTINHTRANGVANCHUYEN, 
						MAKH=NMAKH,
						MACTPD=NMACTPD
				WHERE MAHANHLY=NMAHANHLY;
	SELECT 'THANH CONG' AS '';
    END;
    END IF;
END$$
DELIMITER ;
CALL CHINHSUA_TT_HANHLY('HL001','DO','OK','KH001','CTPD1');
-- ----------------------------------------------------------------------------------------------------
-- CHINH SUA THONG TIN DAILYTRUNGGIAN
DELIMITER $$
DROP PROCEDURE IF EXISTS CHINHSUA_TT_DAILYTRUNGGIAN; 
CREATE PROCEDURE CHINHSUA_TT_DAILYTRUNGGIAN(NMADLTG varchar(5),
											NTENDLTG varchar(50))
BEGIN
	IF NMADLTG NOT IN (SELECT MADLTG FROM DAILYTRUNGGIAN) OR NMADLTG IS NULL
	THEN   
		BEGIN 
			SELECT 'DAI LY TRUNG GIAN KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
	BEGIN
	UPDATE DAILYTRUNGGIAN	SET	TENDLTG=NTENDLTG
							WHERE MADLTG=NMADLTG;
	SELECT 'THANH CONG' AS '';
    END;
    END IF;
END$$
DELIMITER ;
CALL CHINHSUA_TT_DAILYTRUNGGIAN('DL001','DAI LI 1');
-- ----------------------------------------------------------------------------------------------------
-- XOA CHI TIET HOA DON
DELIMITER $$
DROP PROCEDURE IF EXISTS XOA_CHITIETHOADON; 
CREATE PROCEDURE XOA_CHITIETHOADON(NMAHD varchar(5), NMAPHIEUSD varchar(5))
BEGIN
	IF (SELECT COUNT(MAPHIEUSD)FROM CHITIETHOADON WHERE MAHD=NMAHD AND MAPHIEUSD=NMAPHIEUSD)=0
	THEN   
		BEGIN 
			SELECT 'CHI TIET KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
		BEGIN
		DELETE FROM CHITIETHOADON WHERE MAHD=NMAHD AND MAPHIEUSD=NMAPHIEUSD;
		SELECT 'THANH CONG' AS '';
		END;
    END IF;
END$$
DELIMITER ;
CALL XOA_CHITIETHOADON('HD19','PSD04');
-- ----------------------------------------------------------------------------------------------------
-- CHINH SUA THONG TIN DAILYTRUNGGIAN
DELIMITER $$
DROP PROCEDURE IF EXISTS CHINHSUA_TT_CHITIETPHIEUDAT; 
CREATE PROCEDURE CHINHSUA_TT_CHITIETPHIEUDAT(
		NMACTPD varchar(10), 
		NLOAIPHONG varchar(20) ,
		NSLNGUOILON int ,
		NSLTRE int ,
		NGIACOBAN float ,
		NTGBATDAU date ,
		NTGKETTHUC date ,
		NMAPHONG varchar(5) ,
		NMAPDP varchar(5))
BEGIN
	IF NMACTPD NOT IN (SELECT MACTPD FROM CHITIETPHIEUDAT) OR NMACTPD IS NULL
	THEN   
		BEGIN 
			SELECT 'CHI TIET PHIEU DAT KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSEIF NMAPHONG NOT IN (SELECT MAPHONG FROM PHONG) OR NMAPHONG IS NULL
	THEN   
		BEGIN 
			SELECT 'PHONG KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSEIF NMAPDP NOT IN (SELECT MAPDP FROM PHIEUDATPHONG) OR NMAPDP IS NULL
	THEN   
		BEGIN 
			SELECT 'PHIEU DAT PHONG KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
		BEGIN
		UPDATE CHITIETPHIEUDAT	SET	LOAIPHONG=NLOAIPHONG,
									SLNGUOILON=NSLNGUOILON,
									SLTRE=NSLTRE,
									GIACOBAN=NGIACOBAN ,
									TGBATDAU=NTGBATDAU ,
									TGKETTHUC=NTGKETTHUC ,
									MAPHONG=NMAPHONG ,
									MAPDP=NMAPDP
								WHERE MACTPD=NMACTPD;
		SELECT 'THANH CONG' AS '';
		END;
    END IF;
END$$
DELIMITER ;
CALL CHINHSUA_TT_CHITIETPHIEUDAT('CTPD1','A',1,1,1,'2023-03-03','2023-03-03','P0001','DP001');
-- ----------------------------------------------------------------------------------------------------
-- THEM HOA DON
DELIMITER $$
DROP PROCEDURE IF EXISTS CHINHSUA_TT_HOADON;
CREATE PROCEDURE CHINHSUA_TT_HOADON (
		NMAHD VARCHAR(5),
		NNGAYLAP date ,
		NGIATONG float ,
		NTONGTIEN float ,
		NTINHTRANG varchar(20) ,
		NDANHGIA varchar(100) ,
		NMAKH varchar(5) ,
		NMANV varchar(5) ,
		NMAPHONG varchar(5))
BEGIN
DECLARE NUM INT;
	IF NMAHD NOT IN (SELECT MAHD FROM HOADON) OR NMAHD IS NULL
	THEN   
		BEGIN 
			SELECT 'HOA DON KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSEIF NMAKH NOT IN (SELECT MAKH FROM KHACHHANG) OR NMAKH IS NULL
	THEN   
		BEGIN 
			SELECT 'KHACH HANG KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSEIF NMANV NOT IN (SELECT MANV FROM NHANVIEN) OR NMANV IS NULL
	THEN   
		BEGIN 
			SELECT 'NHAN VIEN KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSEIF NMAPHONG NOT IN (SELECT MAPHONG FROM PHONG) OR NMAPHONG IS NULL
	THEN   
		BEGIN 
			SELECT 'PHONG KHONG TON TAI' AS '';
			ROLLBACK;
        END;
	ELSE
		BEGIN
			UPDATE HOADON	SET	NGAYLAP =NNGAYLAP ,
								GIATONG = NGIATONG  ,
								TONGTIEN = NTONGTIEN  ,
								TINHTRANG = NTINHTRANG ,
								DANHGIA = NDANHGIA ,
								MAKH = NMAKH ,
								MANV = NMANV ,
								MAPHONG = NMAPHONG
								WHERE MAHD =NMAHD;
			SELECT 'THANH CONG' AS '';
		END;
    END IF;
END$$
DELIMITER ;
CALL CHINHSUA_TT_HOADON('HD26','2023-03-03',1,1,'A','A','KH001','LT001','P0001');
-- ----------------------------------------------------------------------------------------------------

