-- XEM DANH SACH SAN PHAM
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_SANPHAM;
CREATE PROCEDURE XEM_DS_SANPHAM()
BEGIN
	SELECT * FROM SANPHAM;
END$$
DELIMITER ;
CALL XEM_DS_SANPHAM();
-- ----------------------------------------------------------------------------------------------------
-- XEM DANH SACH KHACH HANG
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_KHACHHANG;
CREATE PROCEDURE XEM_DS_KHACHHANG()
BEGIN
	SELECT * FROM KHACHHANG;
END$$
DELIMITER ;
CALL XEM_DS_KHACHHANG;
-- ----------------------------------------------------------------------------------------------------
-- XEM DANH SACH PHONG
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_PHONG;
CREATE PROCEDURE XEM_DS_PHONG()
BEGIN
	SELECT * FROM PHONG;
END$$
DELIMITER ;
CALL XEM_DS_PHONG;
-- ----------------------------------------------------------------------------------------------------
-- XEM DANH SACH DICH VU LU HANH
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_DICHVULUHANH;
CREATE PROCEDURE XEM_DS_DICHVULUHANH()
BEGIN
	SELECT * FROM DICHVULUHANH;
END$$
DELIMITER ;
CALL XEM_DS_DICHVULUHANH;
-- ----------------------------------------------------------------------------------------------------
-- XEM DANH SACH DICH VU KHACH SAN
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_DICHVUKHACHSAN;
CREATE PROCEDURE XEM_DS_DICHVUKHACHSAN()
BEGIN
	SELECT * FROM DICHVUKHACHSAN;
END$$
DELIMITER ;
CALL XEM_DS_DICHVUKHACHSAN;
-- ----------------------------------------------------------------------------------------------------
-- XEM DS DOI TAC LU HANH
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_DOITACLUHANH;
CREATE PROCEDURE XEM_DS_DOITACLUHANH()
BEGIN
	SELECT * FROM DOITACLUHANH;
END$$
DELIMITER ;
CALL XEM_DS_DOITACLUHANH;
-- ----------------------------------------------------------------------------------------------------
-- XEM DS NHAN VIEN
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_NHANVIEN;
CREATE PROCEDURE XEM_DS_NHANVIEN()
BEGIN
	SELECT * FROM NHANVIEN;
END$$
DELIMITER ;
CALL XEM_DS_NHANVIEN;
-- XEM THONG TIN LE TAN
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_LETAN;
CREATE PROCEDURE XEM_DS_LETAN()
BEGIN
	SELECT * FROM NHANVIEN WHERE CHUCVU='LE TAN';
END$$
DELIMITER ;
CALL XEM_DS_LETAN();
-- XEM THONG TIN BELLMAN
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_BELLMAN;
CREATE PROCEDURE XEM_DS_BELLMAN()
BEGIN
	SELECT * FROM NHANVIEN WHERE CHUCVU='BELLMAN';
END$$
DELIMITER ;
CALL XEM_DS_BELLMAN();
-- XEM THONG TIN NHAN VIEN DICH VU
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_NVDICHVU;
CREATE PROCEDURE XEM_DS_NVDICHVU()
BEGIN
	SELECT * FROM NHANVIEN WHERE CHUCVU='DICH VU';
END$$
DELIMITER ;
CALL XEM_DS_NVDICHVU();
-- XEM THONG TIN NHAN VIEN BAO VE
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_NVBAOVE;
CREATE PROCEDURE XEM_DS_NVBAOVE()
BEGIN
	SELECT * FROM NHANVIEN WHERE CHUCVU='BAO VE';
END$$
DELIMITER ;
CALL XEM_DS_NVBAOVE();
-- XEM THONG TIN NHAN VIEN KE TOAN
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_NVKETOAN;
CREATE PROCEDURE XEM_DS_NVKETOAN()
BEGIN
	SELECT * FROM NHANVIEN WHERE CHUCVU='KE TOAN';
END$$
DELIMITER ;
CALL XEM_DS_NVKETOAN();
-- XEM THONG TIN NHAN VIEN VE SINH
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_NVVESINH;
CREATE PROCEDURE XEM_DS_NVVESINH()
BEGIN
	SELECT * FROM NHANVIEN WHERE CHUCVU='VE SINH';
END$$
DELIMITER ;
CALL XEM_DS_NVVESINH();
-- ----------------------------------------------------------------------------------------------------
-- XEM DANH SACH DOAN
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_DOAN;
CREATE PROCEDURE XEM_DS_DOAN()
BEGIN
	SELECT * FROM DOAN;
END$$
DELIMITER ;
CALL XEM_DS_DOAN;
-- ----------------------------------------------------------------------------------------------------
-- XEM DANH SACH PHIEU SU DUNG
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_PHIEUSUDUNG;
CREATE PROCEDURE XEM_DS_PHIEUSUDUNG()
BEGIN
	SELECT * FROM PHIEUSUDUNG;
END$$
DELIMITER ;
CALL XEM_DS_PHIEUSUDUNG;
-- ----------------------------------------------------------------------------------------------------
-- XEM DS PHIEU DAT PHONG
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_PHIEUDATPHONG;
CREATE PROCEDURE XEM_DS_PHIEUDATPHONG()
BEGIN
	SELECT * FROM PHIEUDATPHONG;
END$$
DELIMITER ;
CALL XEM_DS_PHIEUDATPHONG;
-- ----------------------------------------------------------------------------------------------------
-- XEM DS PHIEU DANG KY NHAN PHONG
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_PHIEUDANGKYNHANPHONG;
CREATE PROCEDURE XEM_DS_PHIEUDANGKYNHANPHONG()
BEGIN
	SELECT * FROM PHIEUDANGKYNHANPHONG;
END$$
DELIMITER ;
CALL XEM_DS_PHIEUDANGKYNHANPHONG;
-- ----------------------------------------------------------------------------------------------------
-- XEM DS HANH LY
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_HANHLY;
CREATE PROCEDURE XEM_DS_HANHLY()
BEGIN
	SELECT * FROM HANHLY;
END$$
DELIMITER ;
CALL XEM_DS_HANHLY;
-- ----------------------------------------------------------------------------------------------------
-- XEM DS DAI LY TRUNG GIAN 
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_DAILYTRUNGGIAN;
CREATE PROCEDURE XEM_DS_DAILYTRUNGGIAN()
BEGIN
	SELECT * FROM DAILYTRUNGGIAN;
END$$
DELIMITER ;
CALL XEM_DS_DAILYTRUNGGIAN;
-- ----------------------------------------------------------------------------------------------------
-- XEM DS CHI TIET HOA DON
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_CHITIETHOADON;
CREATE PROCEDURE XEM_DS_CHITIETHOADON()
BEGIN
	SELECT * FROM CHITIETHOADON;
END$$
DELIMITER ;
CALL XEM_DS_CHITIETHOADON;
-- ----------------------------------------------------------------------------------------------------
-- XEM DS CHI TIET PHIEU DAT
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_CHITIETPHIEUDAT;
CREATE PROCEDURE XEM_DS_CHITIETPHIEUDAT()
BEGIN
	SELECT MACTPD, LOAIPHONG, SLNGUOILON, SLTRE, GIACOBAN, TGBATDAU, TGKETTHUC, MAPHONG, MAPDP FROM CHITIETPHIEUDAT;
END$$
DELIMITER ;
CALL XEM_DS_CHITIETPHIEUDAT;
-- ----------------------------------------------------------------------------------------------------
-- XEM DS CHI TIET HOA DON
DELIMITER $$
DROP PROCEDURE IF EXISTS XEM_DS_HOADON;
CREATE PROCEDURE XEM_DS_HOADON()
BEGIN
	SELECT MAHD, NGAYLAP, GIATONG, TONGTIEN, TINHTRANG, DANHGIA, MAKH, MANV, MAPHONG FROM HOADON;
END$$
DELIMITER ;
CALL XEM_DS_HOADON;
-- ----------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------

ALTER TABLE HOADON ADD COLUMN A INT;
DELIMITER $$  
drop procedure if exists CHINHSUA_HD;
CREATE PROCEDURE CHINHSUA_HD()
BEGIN
DECLARE n INT DEFAULT 0;
DECLARE i INT DEFAULT 0;
SELECT COUNT(*) FROM HOADON INTO n;
SET i=1;
WHILE i<n+1 DO 
  UPDATE HOADON SET A=i where MAHD=CONCAT('HD',i);
  SET i = i + 1;
END WHILE;
End $$
DELIMITER ;
call CHINHSUA_HD();
-- -------------------------------------------------------
-- CHITIETPHIEUDAT
ALTER TABLE CHITIETPHIEUDAT ADD COLUMN A INT;
DELIMITER $$  
drop procedure if exists CHINHSUA_CHITIETPHIEUDAT;
CREATE PROCEDURE CHINHSUA_CHITIETPHIEUDAT()
BEGIN
DECLARE n INT DEFAULT 0;
DECLARE i INT DEFAULT 0;
SELECT COUNT(*) FROM CHITIETPHIEUDAT INTO n;
SET i=1;
WHILE i<n+1 DO 
  UPDATE CHITIETPHIEUDAT SET A=i where MACTPD=CONCAT('CTPD',i);
  SET i = i + 1;
END WHILE;
End $$
DELIMITER ;
call CHINHSUA_CHITIETPHIEUDAT();


/*
SELECT  routine_name,  
        routine_type 
FROM information_schema.routines 
WHERE routine_schema = 'DA_PTTK' AND routine_name LIKE 'XEM_TT_%'
ORDER BY routine_name;*/